# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-06 17:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Alergies_Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 6, 17, 23, 34, 10771, tzinfo=utc)),
        ),
    ]
