# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-06 17:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Alergies_Blog', '0003_auto_20170606_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 6, 17, 24, 10, 257239, tzinfo=utc)),
        ),
    ]
