# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-07 16:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Alergies_Blog', '0004_auto_20170606_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 16, 45, 53, 264932, tzinfo=utc)),
        ),
    ]
