# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-09 19:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Alergies_Blog', '0005_auto_20170607_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog_pictures'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 9, 19, 17, 17, 12065, tzinfo=utc)),
        ),
    ]
