# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-12 17:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Alergies_Blog', '0009_auto_20170612_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 12, 17, 12, 25, 802846, tzinfo=utc)),
        ),
    ]
